import type { Metadata } from "next";
import { Jersey_20 } from "next/font/google";
import { Suspense } from 'react';
import "./globals.css";

const geistSans = Jersey_20({
  subsets: ['latin', 'latin-ext'],
  weight: '400'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} antialiased`}
      >
        <Suspense>
        {children}
        </Suspense>
      </body>
    </html>
  );
}
