import type { Metadata } from "next";
import { Geist, Geist_Mono, Doto } from "next/font/google";
import { Suspense } from 'react';
import "./globals.css";

const geistSans = Doto({
  weight: '600'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} antialiased`}
      >
        <Suspense>
        {children}
        </Suspense>
      </body>
    </html>
  );
}
